version: '3.4'

services:
  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
      - "10000:8080"
  redis:
    image: redis:4-alpine3.9
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:10.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpassword
      POSTGRES_DB: mydbname
