spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydbname
    username: mydbuser
    password: mydbpassword

docker:
  host: "${DOCKER_IP:localhost}"

eureka:
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${docker.host}:10000/eureka/v2/